language: node_js
node_js:
  - 8
  - 7
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: yarn run test-cov
after_script:
  - greenkeeper-lockfile-upload
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8